CREATE TABLE IF NOT EXISTS shipments (
    id                        BIGINT       NOT NULL AUTO_INCREMENT,
    auction_bid_id            BIGINT       NOT NULL,
    user_id                   BIGINT       NOT NULL,
    tracking_number           VARCHAR(100) NULL,
    courier_code              VARCHAR(50)  NULL,
    delivery_proof_image_path VARCHAR(500) NULL,
    shipped_at                DATETIME     NULL,
    received_at               DATETIME     NULL,
    buyer_address_id        BIGINT         NULL,
    seller_address_id       BIGINT         NULL,
    buyer_address_snapshot  JSON           NULL,
    seller_address_snapshot JSON           NULL,
    service_code            VARCHAR(20)    NULL,
    shipping_cost           DECIMAL(15,2)  NULL,
    estimated_costs         JSON           NULL,
    biteship_order_id       VARCHAR(100)   NULL,
    created_at                DATETIME     NOT NULL,
    updated_at                DATETIME     NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_shipments_bid  FOREIGN KEY (auction_bid_id) REFERENCES auction_bids(id),
    CONSTRAINT fk_shipments_user FOREIGN KEY (user_id)        REFERENCES users(id),
    CONSTRAINT fk_shipments_buyer_addr  FOREIGN KEY (buyer_address_id)  REFERENCES user_addresses(id),
    CONSTRAINT fk_shipments_seller_addr FOREIGN KEY (seller_address_id) REFERENCES user_addresses(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
