CREATE TABLE IF NOT EXISTS payment_methods (
    id          BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(100)    NOT NULL UNIQUE,
    type        VARCHAR(100)    NOT NULL,
    name        VARCHAR(255)    NOT NULL,
    is_active   BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;