ALTER TABLE shipments
    DROP INDEX idx_shipments_receive_deadline,
    DROP INDEX idx_shipments_delivered,
    DROP INDEX idx_shipments_ship_deadline,
    DROP INDEX idx_shipments_buyer_address_deadline,
    DROP COLUMN seller_failed_at,
    DROP COLUMN buyer_address_failed_at,
    DROP COLUMN auto_received_at,
    DROP COLUMN delivered_at,
    DROP COLUMN receive_deadline_at,
    DROP COLUMN ship_deadline_at,
    DROP COLUMN buyer_address_deadline_at;
