services:
  app:
    build: .
    container_name: auction_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: auction_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: auction_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auction
      MYSQL_USER: auction
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
  migrate:
    build: .
    image: devonloen/bidify_service_app:production
    networks:
      - app_network
    volumes:
      - ./conf.yml:/home/nonroot/conf.yml:ro   # ← pakai conf khusus docker
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["./migrate"]
    profiles: ["tools"]

  seed:
    build: .
    image: devonloen/bidify_service_app:production
    networks:
      - app_network
    volumes:
      - ./conf.yml:/home/nonroot/conf.yml:ro
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: ["./seed"]
    profiles: ["tools"]

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge