services:
  app:
    build: .
    container_name: auction_app
    ports:
      - "8080:8080"
    env_file:
      - ./dev.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    image: mysql:8.4
    container_name: auction_database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: auction_service
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge