// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Auth"
                ],
                "summary": "Admin Login",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/AuthTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/products/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Products"
                ],
                "summary": "Admin — get all products (paginated)",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AdminProductFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/PaginationResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "nodes": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/ProductResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/products/{productId}/histories": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Products"
                ],
                "summary": "Admin — get status history for any product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "histories": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/ProductStatusHistoryResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Create a new admin user",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AdminCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Get paginated list of users",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AdminUserFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/PaginationResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "nodes": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/UserResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/users/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Get user by ID with roles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "user": {
                                                            "$ref": "#/definitions/UserResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Soft-delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/AuthTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user (requires OTP)",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    }
                }
            }
        },
        "/auth/request-otp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request OTP for phone verification",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AuthOtpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    }
                }
            }
        },
        "/own/files/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Upload a file to temporary storage and return its temporary path",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "path": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/products": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Create a new product listing",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ProductCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "product": {
                                                            "$ref": "#/definitions/ProductResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/products/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Get the authenticated user's own products (paginated)",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OwnProductFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/PaginationResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "nodes": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/ProductResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/products/{productId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Get the authenticated user's own product by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "product": {
                                                            "$ref": "#/definitions/ProductResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Update the authenticated user's own product (only allowed when DRAFT)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OwnProductUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "product": {
                                                            "$ref": "#/definitions/ProductResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/products/{productId}/histories": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Get status history for the caller's own product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "histories": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/ProductStatusHistoryResponse"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/products/{productId}/request": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Request the authenticated user's own product for review (DRAFT → REQUEST)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "product": {
                                                            "$ref": "#/definitions/ProductResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/profiles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Get the authenticated user's own profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "user": {
                                                            "$ref": "#/definitions/UserResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Update the authenticated user's own profile",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OwnProfileUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "user": {
                                                            "$ref": "#/definitions/UserResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/role-requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Submit a new role request (BIDDER or SELLER)",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OwnRoleRequestCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "role_request": {
                                                            "$ref": "#/definitions/RoleRequestResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/own/withdrawal-requests": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Own"
                ],
                "summary": "Submit a new withdrawal request",
                "parameters": [
                    {
                        "description": "Body Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OwnWithdrawalRequestCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "withdrawal_request": {
                                                            "$ref": "#/definitions/WithdrawalRequestResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/products/{productId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get a single product by ID (public)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "productId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/DataResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "product": {
                                                            "$ref": "#/definitions/ProductResponse"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/storage/public/{filePath}": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "File"
                ],
                "summary": "Serve a presigned local file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "File path",
                        "name": "filePath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "AdminCreateRequest": {
            "type": "object",
            "required": [
                "birth",
                "fullname",
                "password",
                "phone"
            ],
            "properties": {
                "birth": {
                    "type": "string",
                    "example": "1990-01-15"
                },
                "fullname": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Admin User"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "MALE",
                        "FEMALE"
                    ],
                    "example": "MALE"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "+6281234567891"
                }
            }
        },
        "AdminProductFetchRequest": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PRELOVED"
                    ],
                    "example": "NEW"
                },
                "limit": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "search": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "laptop"
                },
                "sorts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "direction",
                            "field"
                        ],
                        "properties": {
                            "direction": {
                                "type": "string",
                                "enum": [
                                    "asc",
                                    "desc"
                                ],
                                "example": "desc"
                            },
                            "field": {
                                "type": "string",
                                "enum": [
                                    "id",
                                    "name",
                                    "status",
                                    "condition",
                                    "created_at",
                                    "updated_at"
                                ],
                                "example": "created_at"
                            }
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "DRAFT",
                        "REQUEST",
                        "VERIFIED",
                        "REJECTED",
                        "ON_BIDS",
                        "COMPLETED"
                    ],
                    "example": "VERIFIED"
                }
            }
        },
        "AdminUserFetchRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "ADMIN",
                        "BIDDER",
                        "SELLER",
                        "SUPERADMIN"
                    ],
                    "example": "BIDDER"
                },
                "sorts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "direction",
                            "field"
                        ],
                        "properties": {
                            "direction": {
                                "type": "string",
                                "enum": [
                                    "asc",
                                    "desc"
                                ],
                                "example": "desc"
                            },
                            "field": {
                                "type": "string",
                                "enum": [
                                    "id",
                                    "fullname",
                                    "phone",
                                    "birth",
                                    "gender",
                                    "created_at",
                                    "updated_at"
                                ],
                                "example": "created_at"
                            }
                        }
                    }
                }
            }
        },
        "AuthLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "+6281234567890"
                }
            }
        },
        "AuthOtpRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "+6281234567890"
                }
            }
        },
        "AuthRegisterRequest": {
            "type": "object",
            "required": [
                "birth",
                "fullname",
                "otp",
                "password",
                "phone"
            ],
            "properties": {
                "birth": {
                    "type": "string",
                    "example": "1990-01-15"
                },
                "fullname": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "MALE",
                        "FEMALE"
                    ],
                    "example": "MALE"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8,
                    "example": "password123"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "+6281234567890"
                }
            }
        },
        "AuthTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "DataResponse": {
            "type": "object",
            "additionalProperties": true
        },
        "OwnProductFetchRequest": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PRELOVED"
                    ],
                    "example": "NEW"
                },
                "limit": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "search": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "laptop"
                },
                "sorts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "direction",
                            "field"
                        ],
                        "properties": {
                            "direction": {
                                "type": "string",
                                "enum": [
                                    "asc",
                                    "desc"
                                ],
                                "example": "desc"
                            },
                            "field": {
                                "type": "string",
                                "enum": [
                                    "id",
                                    "name",
                                    "status",
                                    "condition",
                                    "created_at",
                                    "updated_at"
                                ],
                                "example": "created_at"
                            }
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "DRAFT",
                        "REQUEST",
                        "VERIFIED",
                        "REJECTED",
                        "ON_BIDS",
                        "COMPLETED"
                    ],
                    "example": "VERIFIED"
                }
            }
        },
        "OwnProductUpdateRequest": {
            "type": "object",
            "required": [
                "condition",
                "name"
            ],
            "properties": {
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PRELOVED"
                    ],
                    "example": "NEW"
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000,
                    "example": "A beautiful vintage camera"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Vintage Camera"
                }
            }
        },
        "OwnProfileUpdateRequest": {
            "type": "object",
            "required": [
                "birth",
                "fullname",
                "phone"
            ],
            "properties": {
                "bank_account_number": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "1234567890"
                },
                "birth": {
                    "type": "string",
                    "example": "1990-01-15"
                },
                "fullname": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "MALE",
                        "FEMALE"
                    ],
                    "example": "MALE"
                },
                "nik": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "3201010101010001"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 20,
                    "example": "+6281234567890"
                }
            }
        },
        "OwnRoleRequestCreateRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "bank_account_number": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "1234567890"
                },
                "identity_image_path": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "/uploads/identity.jpg"
                },
                "nik": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "3201010101010001"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "BIDDER",
                        "SELLER"
                    ],
                    "example": "BIDDER"
                },
                "selfie_identity_image_path": {
                    "type": "string",
                    "maxLength": 500,
                    "example": "/uploads/selfie.jpg"
                }
            }
        },
        "OwnWithdrawalRequestCreateRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 500000
                }
            }
        },
        "PaginationResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "nodes": {},
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 24
                }
            }
        },
        "ProductCreateRequest": {
            "type": "object",
            "required": [
                "condition",
                "name"
            ],
            "properties": {
                "condition": {
                    "type": "string",
                    "enum": [
                        "NEW",
                        "PRELOVED"
                    ],
                    "example": "NEW"
                },
                "description": {
                    "type": "string",
                    "maxLength": 2000,
                    "example": "A beautiful vintage camera"
                },
                "image_count": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 0,
                    "example": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "example": "Vintage Camera"
                }
            }
        },
        "ProductResponse": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string",
                    "example": "NEW"
                },
                "cover_image_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "A beautiful vintage camera"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "image_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "Vintage Camera"
                },
                "status": {
                    "type": "string",
                    "example": "DRAFT"
                },
                "status_histories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ProductStatusHistoryResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/UserResponse"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "ProductStatusHistoryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "Looks good!"
                },
                "product_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "status": {
                    "type": "string",
                    "example": "VERIFIED"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "Response": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "RoleRequestResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "message": {
                    "type": "string",
                    "example": "Please review my request"
                },
                "role": {
                    "type": "string",
                    "example": "BIDDER"
                },
                "status": {
                    "type": "string",
                    "example": "REQUESTED"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "UserResponse": {
            "type": "object",
            "properties": {
                "bank_account_number": {
                    "type": "string"
                },
                "birth": {
                    "type": "string",
                    "example": "1990-01-15T00:00:00Z"
                },
                "created_at": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string",
                    "example": "John Doe"
                },
                "gender": {
                    "type": "string",
                    "example": "MALE"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "identity_image_link": {
                    "type": "string"
                },
                "is_deleted": {
                    "type": "boolean",
                    "example": false
                },
                "is_verified": {
                    "type": "boolean",
                    "example": false
                },
                "nik": {
                    "type": "string"
                },
                "phone": {
                    "type": "string",
                    "example": "+6281234567890"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/UserRoleResponse"
                    }
                },
                "selfie_identity_image_link": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "UserRoleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "role": {
                    "type": "string",
                    "example": "ADMIN"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "WithdrawalRequestResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 500000
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "status": {
                    "type": "string",
                    "example": "REQUESTED"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "validator_user_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Auction Service API",
	Description:      "Auction Service REST API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
